---
abstract: 'Stripe API bindings'
author:
  - 'Naveed Massjouni <naveed@vt.edu>'
build_requires:
  Exporter: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  JSON: 0
  Test::Modern: 0
  Test::More: 0
  perl: v5.14.0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Stripe
requires:
  Carp: 0
  Method::Signatures: 0
  Moo: 0
  WebService::Client: 0.0202
resources:
  bugtracker: https://github.com/Crowdtilt/WebService-Stripe/issues
  repository: git://github.com/Crowdtilt/WebService-Stripe.git
version: 0.0300
